### ISSUE TITLE
ReferenceError: defaultAction is not defined with generated site

### ISSUE THREAD

**Issue by ghusse** [taunus/generator-taunus#2]
Hi,

I used this generator to see what I could do with taunus:
1. I installed yo & generator-taunus
2. ran `yo taunus`
3. launched the serveur `npm start`

And got this error:

```
ReferenceError: defaultAction is not defined
    at jsonx (node_modules/taunus/lib/render.js:69:20)
    at render (node_modules/taunus/lib/render.js:44:5)
    at deferred (node_modules/taunus/lib/render.js:164:12)
    at Object.defer [as render] (node_modules/taunus/lib/render.js:159:5)
    at render node_modules/taunus-express/taunus-express.js:19:14)
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:82:5)
    at next (node_modules/express/lib/router/route.js:110:13)
    at module.exports (controllers/home/index.js:17:3)
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:82:5)
    at next (node_modules/express/lib/router/route.js:110:13)
```

The app seems to be rendered, but I tried to add another view, and could not manage to have a correct client-side rendering (I don't know if it is linked to this error).

As I don't know if this issue is related to the generator himself, or if it's a bug in taunus.

**Comment by bevacqua** [comment]
Give `1.2.2` a shot, let me know if that fixes it. Issue was dependency mismatch between `taunus` and `taunus-express`

**Comment by ghusse** [comment]
I don't know if it is related, but now I have error during the installation of `generator-taunus`

```
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.38"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/generator-taunus/node_modules/taunus/node_modules/hget/node_modules/html-md/node_modules/jsdom/node_modules/contextify/.node-gyp"
```

On debian Wheezy.

After that, the generation fails

``` events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot call method 'copy' of undefined
    at cp (/usr/lib/node_modules/generator-taunus/app/index.js:26:18)
    at Array.forEach (native)
    at yeoman.generators.Base.extend.writing.app (/usr/lib/node_modules/generator-taunus/app/index.js:19:37)
    at /usr/lib/node_modules/generator-taunus/node_modules/yeoman-generator/lib/base.js:412:16
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by bevacqua** [comment]
You should use `nvm` for versioning. It'll save you headaches

**Comment by ghusse** [comment]
Versionning what? I don't need to upgrade node, just your package!

**Comment by bevacqua** [comment]
You are having `node-gyp` issues because you have Node installed as root
