### ISSUE TITLE
Error running generator (Node v0.10.38)

### ISSUE THREAD

**Issue by ivancevich** [taunus/generator-taunus#3]
Hi @bevacqua 
I'm trying to start playing with Taunus, but I'm getting this error when running the Yeoman generator.
I've only tested it with Node v0.10.38
This is the error I'm getting:

```
~/Documents/Developer/Isomorphics/ yo taunus

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |   That is the fanciest   |
   `---------´   |     Taunus generator!    |
    ( _´U`_ )    '--------------------------'
    /___A___\
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

(!) #src() and #dest() are deprecated. Please read the documentation to learn about
the new ways of handling files. http://yeoman.io/authoring/file-system.html

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot call method 'copy' of undefined
    at cp (/Users/jcivancevich/.nvm/v0.10.38/lib/node_modules/generator-taunus/app/index.js:26:18)
    at Array.forEach (native)
    at yeoman.generators.Base.extend.writing.app (/Users/jcivancevich/.nvm/v0.10.38/lib/node_modules/generator-taunus/app/index.js:19:37)
    at /Users/jcivancevich/.nvm/v0.10.38/lib/node_modules/generator-taunus/node_modules/yeoman-generator/lib/base.js:412:16
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

Thanks!

**Comment by ivancevich** [comment]
Fixed
